module.exports = {
  file: 'script-siti-vetrina.docx',
  title: 'Siti vetrina',
  product: 'Lo usiamo tutti e tre — Giulia, Gabriele, Edoardo. Dove c’è [nome] ci va il tuo.',
  objective: '**Obiettivo: farti dare il numero WhatsApp per mandare la bozza.** Non l’appuntamento, non il prezzo, non il sì al sito. **Tu non chiudi mai**: chiude Patrick.\n\nQuello che sta **fra virgolette si dice**. Il resto è per capire, e si legge una volta a casa.',
  blocks: [
    { t: 'h', text: 'LA CHIAMATA' },

    { t: 'h', text: '1 · Apri' },
    { t: 'say', lines: ['Buongiorno, parlo con [nome dell’attività]?', '(aspetta il sì)', 'Sono [nome], di DenkiCode. La disturbo?'] },
    { t: 'note', text: 'Quasi tutti rispondono *«no, mi dica»*. Se dice **sì**, non si insiste: si guadagna un appuntamento telefonico, che vale più di due minuti strappati.' },
    { t: 'say', lines: ['Immaginavo, chiamo a caso. Le va meglio se la richiamo dopo le [ora]?'] },
    { t: 'note', text: 'Poi si segna **Richiamare** e l’ora, e si saluta.' },

    { t: 'h', text: '2 · Aggancia', tag: 'qui si legge la nota della lista' },
    { t: 'say', lines: ['La chiamo perché prima di telefonare vi ho cercati su Google, e…'] },
    { t: 'table', widths: [2900, 6840], head: ['Se in lista c’è scritto', 'Si finisce la frase così'],
      rows: [
        ['Nessun sito', '…un vostro sito non l’ho trovato. C’è Facebook, ci sono le schede degli altri, ma un sito vostro no.'],
        ['Sito vecchio', '…il vostro sito l’ho aperto dal telefono: viene fuori piccolo, per leggerlo devo allargare con le dita.'],
        ['Dominio morto', '…ho provato ad aprire [dominio] e non si apre più.'],
        ['Scheda Google, Wix, Jimdo', '…quello che si apre non è un sito vostro: è una scheda di Google. L’indirizzo lo dice.'],
      ] },
    { t: 'note', text: 'Non è un complimento e non è un’accusa: è una **constatazione**. Detta piano, senza soddisfazione. Poi **due secondi di silenzio**.' },

    { t: 'h', text: '3 · Fallo parlare' },
    { t: 'say', lines: ['Le faccio una domanda sola: quante volte alla settimana vi chiamano solo per sapere gli orari, o dove siete di preciso?', '(lascia rispondere — quasi tutti dicono "eh, sempre")', 'E quelli che invece non chiamano, secondo lei dove vanno?'] },
    { t: 'note', text: '**La seconda domanda è la telefonata.** Non serve che risponda con un numero: serve che ci pensi due secondi. **Non rispondere al posto suo.**' },

    { t: 'h', text: '4 · Di’ cosa facciamo' },
    { t: 'say', lines: ['Ecco perché la chiamo. Siamo DenkiCode, siamo di Seveso e facciamo siti per le attività qui in zona. Le facciamo vedere come verrebbe il vostro: la prima pagina, con le vostre foto, i vostri orari e il tasto per chiamarvi. Gliela mandiamo su WhatsApp — non costa niente e non la impegna a niente. La guarda, e se non le piace me lo dice e finisce lì.'] },

    { t: 'h', text: '5 · Chiedi, una volta sola' },
    { t: 'say', lines: ['Gliela facciamo? Mi serve solo il numero per WhatsApp: va bene questo, o ne ha un altro?'] },
    { t: 'note', text: 'Mai *«le interesserebbe?»*: è una domanda a cui si dice no senza pensarci. Qui il compito che chiedi è minuscolo — un numero.' },
    { t: 'p', text: 'Se preferisce vedere di persona:' },
    { t: 'say', lines: ['Anche meglio. Le passo il mio collega Patrick, sono dieci minuti: le va meglio [giorno] mattina o [giorno] pomeriggio?'] },

    { t: 'break' },
    { t: 'h', text: 'SE TI DICE… TU DICI' },
    { t: 'obj', q: 'Non mi interessa',
      lines: ['Lo so, non le ho ancora detto niente. Guardi, non le sto vendendo un sito: le sto chiedendo se vuole vedere come verrebbe. È gratis e la guarda quando ha due minuti. Su che numero gliela mando?'] },
    { t: 'obj', q: 'Non ho tempo',
      lines: ['La capisco, e infatti tempo non gliene chiedo: la guarda stasera in tre secondi. Le arriva su questo numero?'],
      note: 'Si riduce **la richiesta**, mai il valore.' },
    { t: 'obj', q: 'Quanto costa?',
      lines: ['Duecento, duecentocinquanta secondo le pagine, una volta sola. Poi c’è una quota annuale di centoventi euro che lo tiene online. Glielo dico subito perché non mi piace girarci intorno — però prima la guardi, poi decide se vale. Su che numero gliela mando?'],
      note: '**Quota annuale**, mai "canone" e mai "abbonamento". Il prezzo è un gancio: **lo aggiusta Patrick**.' },
    { t: 'obj', q: 'Ce l’ho già il sito',
      lines: ['Lo so, l’ho aperto: è per quello che la chiamo. La domanda non è se ce l’ha, è se un cliente dal telefono ci trova gli orari e il tasto per chiamarvi in due secondi. Le mando come lo faremmo noi, così confronta?'],
      note: 'Chi ha già un sito **non è un cliente peggiore**: ha già speso una volta, quindi il valore l’ha capito.' },
    { t: 'obj', q: 'Ci pensa mio nipote',
      lines: ['Meglio così, allora ha già chi glielo tiene. Una domanda sola: l’ultima modifica che gli ha chiesto, in quanto gliel’ha fatta?', '(quasi sempre: "eh, da mesi")', 'Ecco. Noi rispondiamo su WhatsApp in giornata. Gliela mando lo stesso da guardare?'] },
    { t: 'obj', q: 'Mi mandi una mail',
      lines: ['Volentieri. Le dico però come va a finire: la mail resta lì. Su WhatsApp la apre in tre secondi. Le arriva su questo numero?'],
      note: 'Se insiste: si manda davvero, e si segna **Richiamare** con la data.' },
    { t: 'obj', q: 'Chi siete? Non vi conosco',
      lines: ['Giusto, ho chiamato io lei. DenkiCode, siamo di Seveso, facciamo siti e gestionali per le attività qui in zona. Le lascio l’indirizzo così ci guarda con calma: denkicode.com.'] },
    { t: 'obj', q: 'Qualsiasi cosa tu non sappia',
      lines: ['Questo glielo faccio dire direttamente a Patrick.'],
      note: 'Non è una figura barbina: è il modo in cui si passa la palla.' },

    { t: 'break' },
    { t: 'h', text: 'DOPO LA CHIAMATA', tag: 'nel foglio, prima una di queste sei parole' },
    { t: 'p', text: '**Non risponde · Richiamare · Non è il decisore · No · Troppo piccoli · Fissato incontro**' },
    { t: 'note', text: 'Poi scrivici accanto quello che vuoi. Se davanti non c’è una di queste sei parole, la domenica i numeri non si contano e la settimana dopo si lavora alla cieca.' },
    { t: 'p', text: 'Se ha detto sì, servono quattro cose o Patrick arriva cieco:' },
    { t: 'list', ordered: true, items: [
      'il **numero WhatsApp** per la bozza',
      '**chi decide**, e come si chiama',
      'la **frase con cui ha ammesso il problema** — le sue parole, non le tue',
      'cosa ha oggi: niente, sito vecchio, solo Facebook, ci pensa un parente',
    ] },
    { t: 'h', text: 'Il messaggio, entro cinque minuti' },
    { t: 'say', lines: ['Buongiorno [Nome], sono [nome] di DenkiCode — ci siamo sentiti ora. Passo il suo numero al mio collega Patrick: le prepara la prima pagina del sito come la vedrebbe un suo cliente dal telefono e gliela manda qui. Nessun impegno, la guarda con calma.'] },
    { t: 'p', text: 'Se ha detto di no ma non ha sbattuto il telefono, **dopo dieci giorni**, due righe:' },
    { t: 'say', lines: ['Buongiorno [Nome], [nome] di DenkiCode. Avete lasciato perdere l’idea di sistemare il sito?'] },

    { t: 'h', text: 'I QUATTRO DIVIETI' },
    { t: 'list', ordered: true, items: [
      '**Si dà del Lei.** Sempre, anche se dall’altra parte c’è un ragazzo. Al tu ci passa Patrick in riunione, ed è una mossa voluta',
      '**Il prezzo non si aggiusta.** 200-300 € + 120 € l’anno è il gancio per non lasciare la domanda senza risposta. Il numero vero lo fa Patrick',
      '**Le date non si promettono.** Nessuno sa quanto ha in mano Nicola questa settimana',
      '**Niente numeri inventati** ("perde il 30% dei clienti") e mai "fattura", "abbonamento", "contratto": si dice **ricevuta** e **quota annuale**',
    ] },
  ],
};
