module.exports = {
  file: 'script-giulia-indagine.docx',
  title: 'Indagine di mercato',
  product: 'Prodotto D · officine, logistica, impianti, ingrossi, studi, negozi con magazzino',
  objective: '**Qui non vendi niente, e non è un modo di dire: è il flusso.** L’obiettivo unico è il **modulo compilato**. Poi Nicola costruisce un prototipo e Patrick va a venderlo.',
  blocks: [
    { t: 'h', text: 'Perché questa lista si chiama in un altro modo' },
    { t: 'p', text: 'In questa lista **chi telefona non chiede, dà**. È la posizione più forte che hai in tutta la settimana, e l’unica lista in cui un "no" al prodotto non esiste — perché il prodotto non si nomina mai.' },
    { t: 'table', widths: [3100, 6640], head: ['Regola', 'In pratica'],
      rows: [
        ['Sempre del **"Lei"**', 'Anche se dall’altra parte ti danno del tu'],
        ['**Non si vende**', 'Niente prezzi, niente prodotto, niente demo. Se nomini un software la ricerca diventa una scusa e la chiamata muore'],
        ['Il traguardo', 'Il modulo compilato — meglio se lo compili tu mentre siete al telefono'],
        ['Cosa non si chiede', 'Mai fatturato, mai nomi di clienti. Solo che programmi usano e dove perdono tempo'],
        ['Cosa si dà in cambio', 'Il riepilogo di cosa esce dalla zona. **Va mandato davvero**'],
      ] },

    { t: 'h', text: '1. Apertura', tag: 'Voss — il "No", e poi la verità dichiarata' },
    { t: 'say', lines: ['Buongiorno, parlo con [nome dell’azienda]?', '(aspetta il sì)', 'L’ho presa in un momento terribile?', '(no, mi dica)', 'Le dico subito perché chiamo, così non le faccio perdere tempo: non le devo vendere niente, stiamo facendo una ricerca sulle aziende di [settore] qui in [zona] — come gestite ordini, magazzino e rapportini. Sono tre domande.'] },
    { t: 'note', text: '**«Non le devo vendere niente» è vero**, ed è il motivo per cui questa lista funziona diversamente dalle altre due. Se lo dici e poi vendi, la frase è bruciata per tutte le liste future.' },

    { t: 'h', text: '2. Le tre domande', tag: 'SPIN — Situazione e Problema. Una alla volta, aspettando la risposta' },
    { t: 'say', lines: ['1. Oggi ordini e magazzino li tenete su un gestionale, su Excel, o su carta?'] },
    { t: 'say', lines: ['2. E c’è qualcosa che vi tocca ancora rifare a mano due volte — tipo riscrivere in ufficio quello che è già stato scritto in officina?'] },
    { t: 'say', lines: ['3. Se potesse cancellare un lavoro ripetitivo dalla settimana, quale toglierebbe per primo?'] },
    { t: 'note', text: 'Non si legge come un questionario: si conversa. **La terza è quella che vale la telefonata** — la risposta a quella domanda è il capitolato del prototipo che scriverà Nicola. Poi silenzio.' },

    { t: 'h', text: '3. La domanda che apre il valore', tag: 'SPIN — Implicazione' },
    { t: 'say', lines: ['E quante ore alla settimana se ne vanno lì, secondo lei?'] },
    { t: 'note', text: 'Non serve un numero preciso: serve che se lo chiedano ad alta voce. Chi risponde *«troppe»* ha appena detto che il problema esiste, e Patrick lo saprà.' },

    { t: 'h', text: '4. La richiesta' },
    { t: 'p', text: '**Prima strada, la migliore: lo compili tu mentre siete al telefono.**' },
    { t: 'say', lines: ['Guardi, faccio così: queste risposte le metto io nel modulo della ricerca, le rubo altri due minuti e non deve fare niente. Le va?'] },
    { t: 'p', text: '**Seconda strada, se ha fretta o preferisce fare da sé:**' },
    { t: 'say', lines: ['Le mando il link su WhatsApp: sono otto domande, tre minuti, e lo fa quando ha un attimo. Su questo numero?'] },
    { t: 'p', text: '**In cambio si dà qualcosa, sempre** — è una ricerca, non un favore:' },
    { t: 'say', lines: ['Quando abbiamo finito di girare le aziende della zona le mando il riepilogo di cosa è venuto fuori: chi usa cosa, e dove perdono più tempo tutti. Almeno sa come sono messi gli altri.'] },

    { t: 'break' },
    { t: 'h', text: 'Le obiezioni', tag: 'Blount — Accetta, Spiazza, Chiedi' },
    { t: 'obj', q: 'Non ho tempo',
      lines: ['La capisco, chiamo in orario di lavoro. Sono tre domande e le faccio io: non deve compilare niente. Le va se gliele faccio adesso in due minuti, o la richiamo dopo le [orario]?'] },
    { t: 'obj', q: 'A cosa vi serve? Cosa ci guadagnate?',
      lines: ['Domanda giusta. Siamo una software house di Seveso: prima di costruire qualcosa vogliamo capire come lavorano davvero le aziende qui, invece di immaginarcelo dalla scrivania. Se poi da quello che ci dice esce un’idea utile, gliela portiamo — e decide lei se le serve. Intanto le faccio le tre domande?'],
      note: '**Onestà completa.** Non si finge una ricerca universitaria e non si dice "studio di settore indipendente": è una software house che studia il mercato, e detto così regge.' },
    { t: 'obj', q: 'Siamo a posto così, abbiamo già un gestionale',
      lines: ['Buon per voi, è la risposta che sento meno spesso. Proprio per questo mi interessa: quale usate, e cosa vi tocca fare lo stesso a mano nonostante ce l’abbiate?'],
      note: 'Chi ha già un gestionale **è il contatto più prezioso della lista**: sa dove quel gestionale non arriva, e quel buco è il prodotto.' },
    { t: 'obj', q: 'Non compilo moduli online',
      lines: ['Ci mancherebbe, glielo compilo io. Le faccio le domande, metto giù le risposte e lei non tocca niente. Partiamo dalla prima?'] },
    { t: 'obj', q: 'Mi mandi una mail',
      lines: ['Volentieri, le mando il link. Le dico com’è però: i moduli via mail non li apre nessuno, e sarebbe un peccato perché la vostra è esattamente l’azienda che ci serve nella ricerca. Facciamo che gliele faccio adesso e sono due minuti?'] },
    { t: 'obj', q: 'Non do informazioni sull’azienda',
      lines: ['Fa benissimo, e non le chiedo numeri: né fatturato né clienti. Le chiedo solo che programmi usate e cosa vi fa perdere tempo. Su questo posso?'] },

    { t: 'h', text: 'Cosa passo a Patrick', tag: 'valgono anche se il modulo non viene compilato' },
    { t: 'list', ordered: true, items: [
      '**Cosa usano oggi** — gestionale (quale), Excel, carta',
      '**Il doppio lavoro** che hanno ammesso: cosa si riscrive due volte',
      '**Il lavoro ripetitivo** che toglierebbero per primo, *con le sue parole*',
      '**Quante persone** ci lavorano dentro, e chi decide sui programmi',
    ] },

    { t: 'h', text: 'I messaggi dopo la chiamata' },
    { t: 'p', text: '**Modulo compilato al telefono:**' },
    { t: 'say', lines: ['Buongiorno [Nome], sono Giulia di DenkiCode. Grazie per i due minuti: ho messo le sue risposte nella ricerca. Le mando il riepilogo appena abbiamo finito il giro delle aziende della zona.'] },
    { t: 'p', text: '**Ha chiesto il link:**' },
    { t: 'say', lines: ['Buongiorno [Nome], sono Giulia di DenkiCode, ci siamo sentiti ora. Le lascio il modulo della ricerca, sono otto domande e tre minuti: [link] — quando abbiamo finito le mando cosa è venuto fuori dalle aziende della zona.'] },
    { t: 'p', text: '**Link mandato ma non compilato** — dopo sette giorni:' },
    { t: 'say', lines: ['Buongiorno [Nome], Giulia di DenkiCode. Ha lasciato perdere la ricerca?'] },

    { t: 'h', text: 'Il link del modulo', tag: 'da incollare su WhatsApp quando lo chiede' },
    { t: 'p', text: 'https://docs.google.com/forms/d/e/1FAIpQLSe2cCfeAx8IVLRq-ocJe4MUpq43u_1D95IpBPjqOYX-90a9JA/viewform' },
    { t: 'note', text: 'Se il modulo lo compili tu al telefono, si apre lo stesso link e si scrivono le sue risposte. **Se compare un campo con l’email o il consenso, quello è suo**: si chiede, non si mette il nostro.' },

    { t: 'h', text: 'Quello che non si dice mai' },
    { t: 'table', widths: [4200, 5540], head: ['Mai', 'Perché'],
      rows: [
        ['Un prezzo, un prodotto, una demo', 'In questa lista **non si vende**. È tutto il vantaggio della chiamata'],
        ['"gestionale su misura", "sviluppiamo per voi"', 'È il lavoro di Patrick, dopo il prototipo'],
        ['"fattura", "contratto", "abbonamento"', 'Non servono, e sono vietate ovunque'],
        ['"ricerca indipendente", "studio di settore"', 'Siamo una software house, e si dice'],
        ['Promettere il riepilogo se poi non lo mandiamo', 'La promessa costa più di quanto ha reso'],
      ] },
  ],
};
