module.exports = {
  file: 'script-giulia-siti-vetrina.docx',
  title: 'Siti vetrina',
  product: 'Prodotto A · la chiamata dura meno di 40 secondi fino alla domanda',
  objective: '**Obiettivo della chiamata: il sì alla bozza.** Non l’appuntamento, non il prezzo, non la firma. Tu non chiudi mai: chiude Patrick.',
  blocks: [
    { t: 'h', text: 'Le regole, prima di comporre il numero' },
    { t: 'table', widths: [3100, 6640], head: ['Regola', 'In pratica'],
      rows: [
        ['Sempre del **"Lei"**', 'Anche se dall’altra parte ti danno del tu. Tono istituzionale, mai invadente'],
        ['**Non chiudi tu**', 'Il tuo unico traguardo è il sì alla bozza. Il prezzo vero lo fa Patrick'],
        ['Parole vietate', '**Mai** "fattura", "abbonamento", "contratto". Si dice **ricevuta** e **quota annuale**'],
        ['Niente numeri inventati', 'Mai "perde il 30% dei clienti": non l’abbiamo misurato'],
        ['La colonna Note', 'Senza la falla scritta in lista **questa chiamata non funziona**: la si nomina nei primi 10 secondi'],
      ] },

    { t: 'h', text: '1. Apertura', tag: 'Voss — la domanda a cui si risponde "No"' },
    { t: 'say', lines: ['Buongiorno, parlo con [nome dell’attività]?', '(aspetta il sì)', 'L’ho presa in un momento terribile?'] },
    { t: 'note', text: 'Quasi tutti rispondono *«no, mi dica»* — e con quel "no" si sentono di nuovo padroni della telefonata. *«Ha due minuti?»* fa l’opposto: mette in trappola, e il riflesso è riattaccare.' },
    { t: 'p', text: 'Se dice **«sì, sono in mezzo al lavoro»**:' },
    { t: 'say', lines: ['Immaginavo. Quando la richiamo, prima o dopo le [orario]?'] },
    { t: 'note', text: 'Poi si segna **Richiamare** e l’ora. Non si insiste: si è guadagnato un appuntamento telefonico, che vale più di due minuti strappati.' },

    { t: 'h', text: '2. La ragione specifica', tag: 'Gitomer — i compiti fatti a casa' },
    { t: 'say', lines: ['La chiamo perché prima di telefonarle ho guardato la vostra attività dal telefono, come farebbe un cliente: [la falla scritta in lista].'] },
    { t: 'table', widths: [3100, 6640], head: ['Cosa dice la lista', 'Cosa dici tu'],
      rows: [
        ['Nessun sito', '…e ho visto che un sito non ce l’avete: c’è la pagina Facebook e basta.'],
        ['Sito vecchio', '…e il vostro sito dal telefono viene fuori piccolissimo, si legge solo allargando con le dita.'],
        ['Orari sbagliati su Google', '…e su Google i vostri orari dicono una cosa che sulla porta non c’è.'],
      ] },
    { t: 'note', text: 'Non è un complimento e non è un’offesa: è una **constatazione**. Detta piano, senza soddisfazione. Poi due secondi di silenzio.' },

    { t: 'h', text: '3. Il dolore', tag: 'SPIN — Problema, poi Implicazione' },
    { t: 'say', lines: ['Le faccio una domanda sola: quante volte alla settimana vi chiamano solo per chiedere gli orari, o dove siete?', '(ascolta — quasi tutti dicono "eh, sempre")', 'E quelli che invece non chiamano, secondo lei dove vanno a finire?'] },
    { t: 'note', text: 'La seconda è la domanda che vale la telefonata. Nessuno risponde con un numero, e va benissimo: serve che ci pensino per due secondi. Chi dice *«boh, dal concorrente»* si è venduto il problema da solo. **Poi silenzio.**' },

    { t: 'h', text: '4. Il valore anticipato', tag: 'la bozza — si dà prima di chiedere' },
    { t: 'say', lines: ['Ecco perché la chiamo. Siamo una software house qui in Brianza, e lavoriamo così: il mio collega le rifà la prima pagina come la vedrebbe un cliente dal telefono — con i vostri orari, le vostre foto, il tasto per chiamarvi — e gliela mandiamo su WhatsApp. Non costa niente e non impegna a niente: se le piace ne parliamo, se non le piace l’ha vista e amen.'] },
    { t: 'note', text: 'Regge perché **è vero**: la bozza la si fa davvero, in mezza giornata. E sposta la domanda da *«mi vuole vendere un sito»* a *«voglio vedere come verrebbe»*.' },

    { t: 'h', text: '5. La domanda, una sola', tag: 'due strade, tutte e due un sì' },
    { t: 'say', lines: ['Gliela facciamo? Le serve solo dirmi su che numero mandarla — questo o ne ha un altro per WhatsApp?'] },
    { t: 'note', text: 'Mai *«le interesserebbe?»*: è una domanda a cui si dice no senza pensarci. Qui il compito che chiedi è minuscolo — un numero.' },
    { t: 'p', text: 'Se preferisce vedere di persona:' },
    { t: 'say', lines: ['Anche meglio. Passa il mio collega Patrick, dieci minuti: [giorno] mattina o [giorno] pomeriggio?'] },

    { t: 'break' },
    { t: 'h', text: 'Le obiezioni', tag: 'Blount — Accetta, Spiazza, Chiedi. La prima parola è sempre di accettazione' },
    { t: 'obj', q: 'Non mi interessa',
      lines: ['Ci sta, non le ho ancora detto niente. Guardi, le dico com’è: non le sto vendendo un sito, le sto chiedendo se vuole vedere come verrebbe. Gratis, e lo guarda quando ha due minuti. Su che numero glielo mando?'] },
    { t: 'obj', q: 'Non ho tempo',
      lines: ['La capisco, e infatti non le chiedo tempo adesso. La bozza la guarda quando vuole, anche stasera dal divano: sono trenta secondi. Le arriva su questo numero?'],
      note: 'Si riduce **la richiesta**, mai il valore.' },
    { t: 'obj', q: 'Quanto costa?',
      lines: ['Duecento, duecentocinquanta a seconda delle pagine, una volta sola. Poi c’è la quota annuale per tenerlo online e aggiornato, centoventi euro l’anno. Glielo dico subito perché non mi piace girarci intorno — ma prima lo guardi, poi decide se vale. Su che numero le mando la bozza?'],
      note: '**Quota annuale**, mai "canone mensile" e mai "abbonamento". Il prezzo è indicativo: lo aggiusta Patrick.' },
    { t: 'obj', q: 'Ce l’ho già il sito',
      lines: ['Lo so, l’ho guardato — è per quello che la chiamo. La domanda non è se ce l’ha: è se quando lo apre dal telefono un cliente trova gli orari e il tasto per chiamarvi in due secondi. Le mando come lo faremmo noi, così confronta?'],
      note: 'Chi ha già un sito **non è un cliente peggiore**: ha già speso una volta, quindi il valore l’ha capito.' },
    { t: 'obj', q: 'Ci pensa mio nipote / mio cugino',
      lines: ['Meglio così, allora ha già chi glielo tiene. Le faccio una domanda sola: da quanto tempo aspetta la prossima modifica?', '(quasi sempre: "eh, da mesi")', 'Ecco. Noi rispondiamo su WhatsApp in giornata. Glielo mando lo stesso da guardare?'] },
    { t: 'obj', q: 'Mi mandi una mail',
      lines: ['Volentieri. Le dico come va a finire però: la mail resta lì. Su WhatsApp la bozza la apre in tre secondi. Le arriva su questo numero?'],
      note: 'Se insiste: si manda davvero, e si segna **Richiamare** con la data.' },
    { t: 'obj', q: 'Chi siete? Non vi conosco',
      lines: ['Giusto. DenkiCode, siamo di Seveso, facciamo siti e gestionali per le attività qui in zona. Le lascio il sito così ci guarda con calma: denkicode.com — c’è dentro il lavoro che abbiamo fatto per gli altri.'] },

    { t: 'h', text: 'Cosa passo a Patrick', tag: 'nella colonna Esito e Note, dopo la parola d’esito' },
    { t: 'list', items: [
      'Il **numero WhatsApp** su cui mandare la bozza',
      '**Chi decide** — il titolare o qualcun altro, e come si chiama',
      'La **falla che ha ammesso lui**, con le sue parole',
      'Cosa ha oggi: niente sito, sito vecchio, solo Facebook, e chi glielo tiene',
    ] },

    { t: 'h', text: 'I messaggi dopo la chiamata' },
    { t: 'p', text: '**Ha detto sì alla bozza** — entro cinque minuti, mentre si ricorda ancora di te:' },
    { t: 'say', lines: ['Buongiorno [Nome], sono Giulia di DenkiCode, ci siamo sentiti ora. Passo il suo numero al mio collega Patrick: le prepara la prima pagina del sito come la vedrebbe un suo cliente dal telefono e gliela manda qui. Nessun impegno, la guarda con calma.'] },
    { t: 'p', text: '**Ha detto di no, ma non ha chiuso la porta** — dopo dieci giorni, due righe e basta:' },
    { t: 'say', lines: ['Buongiorno [Nome], Giulia di DenkiCode. Avete rinunciato all’idea di sistemare il sito?'] },
    { t: 'note', text: 'È scritta apposta per farsi rispondere *«no, è che…»*: quel "no" riapre la conversazione senza che noi si sia insistito.' },

    { t: 'h', text: 'Quello che non si dice mai' },
    { t: 'table', widths: [4200, 5540], head: ['Mai', 'Perché'],
      rows: [
        ['"fattura", "abbonamento", "contratto"', 'Si dice **ricevuta** e **quota annuale**'],
        ['Una percentuale inventata', 'Non l’abbiamo misurata su di loro'],
        ['Una data di consegna', 'La dà Patrick, dopo aver visto cosa serve'],
        ['Un prezzo diverso da 200-300 € + 120 €/anno', 'Il prezzo vero lo fa Patrick sulla richiesta'],
        ['"Le rifacciamo il sito", prima della bozza', 'Prima si fa vedere, poi si vende'],
      ] },
  ],
};
