module.exports = {
  file: 'script-ecommerce.docx',
  title: 'E-commerce',
  product: 'Lo usiamo tutti e tre — Giulia, Gabriele, Edoardo. Dove c’è [nome] ci va il tuo.',
  objective: '**Obiettivo: farti dare due o tre prodotti e il numero WhatsApp**, per mandare la bozza della vetrina online. Il prezzo del lavoro vero lo fa Patrick.\n\n**Chi c’è in lista**: non chi "potrebbe vendere online", chi **vende già** — in negozio, su Instagram, nei messaggi — e incassa a mano. **Chi il carrello ce l’ha già è cliente di qualcun altro: si salta.**',
  blocks: [
    { t: 'h', text: 'LA CHIAMATA' },

    { t: 'h', text: '1 · Apri' },
    { t: 'say', lines: ['Buongiorno, parlo con [nome dell’attività]?', '(aspetta il sì)', 'Sono [nome], di DenkiCode. La disturbo?'] },
    { t: 'p', text: 'Se dice **sì**:' },
    { t: 'say', lines: ['Immaginavo. Le va meglio se la richiamo dopo le [ora]?'] },
    { t: 'note', text: 'Poi si segna **Richiamare** e l’ora.' },

    { t: 'h', text: '2 · Aggancia', tag: 'si nomina un prodotto vero, quello scritto in lista' },
    { t: 'say', lines: ['La chiamo perché ho guardato la vostra pagina prima di telefonare: avete [il prodotto vero] e le foto sono fatte bene. Però per sapere quanto costa uno vi deve scrivere in privato.'] },
    { t: 'note', text: 'È **l’unica frase della telefonata che un call center non potrebbe mai dire**. Il prodotto si nomina per nome, non "i vostri articoli". Poi **due secondi di silenzio**.' },

    { t: 'h', text: '3 · Fallo parlare' },
    { t: 'say', lines: ['Quanti messaggi vi arrivano al giorno del tipo "quanto viene?" o "ce l’avete la mia taglia?"', '(lascia rispondere — chi dice "eh, tantissimi" si è appena qualificato)', 'E quando siete al banco e rispondete tre ore dopo, secondo lei quello ha aspettato, o l’ha già comprato da un’altra parte?'] },
    { t: 'note', text: '**Il costo non è il sito che non hanno: sono gli ordini che si perdono mentre lavorano.** Quella è la vendita. Poi silenzio.' },
    { t: 'p', text: 'Se il tono resta freddo, una sola in più:' },
    { t: 'say', lines: ['E la sera, quando siete chiusi, chi vi scrive alle undici lo recuperate?'] },

    { t: 'h', text: '4 · Di’ cosa facciamo' },
    { t: 'say', lines: ['Ecco perché la chiamo. Siamo DenkiCode, siamo di Seveso. Facciamo una cosa sola per capirci: prendiamo tre dei vostri prodotti — quelli veri, con le vostre foto — e le facciamo vedere come sarebbero con il prezzo scritto, le taglie e il tasto per pagare. Gliela mandiamo su WhatsApp e non costa niente. Se le piace ne parliamo, se non le piace l’ha vista gratis.'] },
    { t: 'note', text: 'Tre prodotti **veri**, non un modello generico: chi guarda ci si riconosce dentro in due secondi.' },

    { t: 'h', text: '5 · Chiedi, una volta sola' },
    { t: 'say', lines: ['Facciamola. Mi dice due o tre prodotti fra quelli che vendete di più, e su che numero gliela mando?'] },
    { t: 'p', text: 'Se preferisce di persona:' },
    { t: 'say', lines: ['Anche meglio: le passo il mio collega Patrick, viene con la bozza già pronta. [Giorno] mattina o [giorno] pomeriggio?'] },

    { t: 'break' },
    { t: 'h', text: 'SE TI DICE… TU DICI' },
    { t: 'obj', q: 'Non mi interessa vendere online',
      lines: ['La capisco, e non le sto chiedendo di aprire un negozio su internet. Le sto chiedendo se le fa comodo che chi scrive "quanto viene" trovi il prezzo scritto da solo. Su che numero le mando come verrebbe?'] },
    { t: 'obj', q: 'Non ho tempo',
      lines: ['Lo so, e infatti tempo non gliene chiedo: la guarda stasera in tre secondi. Le arriva su questo numero?'] },
    { t: 'obj', q: 'Quanto costa?',
      lines: ['Si parte da cinquecento euro, poi dipende da quanti prodotti sono e da come li spedisce — e c’è una quota annuale. Il numero preciso glielo fa Patrick quando vede cosa le serve. Intanto la bozza gliela facciamo vedere gratis: su che numero?'],
      note: '**La cifra della quota annuale non si dice**: va da 360 a 1.200 € secondo il lavoro. Si dice che c’è, e il numero lo fa Patrick.' },
    { t: 'obj', q: 'Ho già il sito',
      lines: ['Lo so, l’ho aperto: è per quello che la chiamo. La domanda non è se ha il sito, è se uno da lì può comprare senza scrivervi. Le mando tre prodotti vostri con il tasto per pagare, così vede la differenza?'] },
    { t: 'obj', q: 'Vendo già su Instagram / WhatsApp',
      lines: ['Infatti è per quello: vende già, e questo è il pezzo che le manca. Quante ore al giorno se ne vanno a rispondere ai prezzi?', '(ascolta)', 'Ecco, quelle. Le mando come verrebbe?'] },
    { t: 'obj', q: 'Le spedizioni sono un casino',
      lines: ['Domanda giusta, e la risposta gliela dà Patrick meglio di me: si imposta una volta e poi il prezzo lo calcola da solo. Intanto le mando la bozza così vede di cosa parliamo.'] },
    { t: 'obj', q: 'Chi siete? Non vi conosco',
      lines: ['Giusto, ho chiamato io lei. DenkiCode, siamo di Seveso, facciamo siti e gestionali per le attività qui in zona. Le lascio l’indirizzo: denkicode.com.'] },
    { t: 'obj', q: 'Qualsiasi cosa tu non sappia',
      lines: ['Questo glielo faccio dire direttamente a Patrick.'] },

    { t: 'break' },
    { t: 'h', text: 'DOPO LA CHIAMATA', tag: 'nel foglio, prima una di queste sei parole' },
    { t: 'p', text: '**Non risponde · Richiamare · Non è il decisore · No · Troppo piccoli · Fissato incontro**' },
    { t: 'p', text: 'Poi tre cose, o la bozza non si può fare:' },
    { t: 'list', ordered: true, items: [
      'i **due o tre prodotti** che ha nominato lui — con le sue parole',
      'il **numero WhatsApp**',
      '**come incassa oggi**: in negozio, bonifico, messaggi, contrassegno',
    ] },
    { t: 'h', text: 'Il messaggio, entro cinque minuti' },
    { t: 'say', lines: ['Buongiorno [Nome], sono [nome] di DenkiCode — ci siamo sentiti ora. Passo tutto al mio collega Patrick: le prepara [i prodotti che ha detto] come sarebbero con prezzo, taglie e pagamento, e glieli manda qui. Nessun impegno, li guarda con calma.'] },

    { t: 'h', text: 'I QUATTRO DIVIETI' },
    { t: 'list', ordered: true, items: [
      '**La quota annuale non si dice in cifra**: si dice che c’è, il numero lo fa Patrick',
      '**Le percentuali sulle vendite non si nominano mai**',
      '**Si dà del Lei**, e non si promettono date',
      'Mai "abbonamento", "contratto", "fattura": si dice **ricevuta** e **quota annuale**',
    ] },
  ],
};
