module.exports = {
  file: 'script-denkishift.docx',
  title: 'DenkiShift · i turni',
  product: 'Lo usiamo tutti e tre — Giulia, Gabriele, Edoardo. Dove c’è [nome] ci va il tuo.',
  objective: '**Obiettivo: fissare la demo con Patrick.** Dieci minuti, in videochiamata o dal vivo. **Non si vende: si prenota.**\n\nChi c’è in lista: RSA, imprese di pulizie, vigilanza, logistica. Tre filtri, in quest’ordine: **da 8 a 50 dipendenti**, **turni che cambiano**, **azienda indipendente** e non la filiale di una catena.',
  blocks: [
    { t: 'h', text: 'LA CHIAMATA' },

    { t: 'h', text: '1 · Apri' },
    { t: 'say', lines: ['Buongiorno, parlo con [nome della struttura]?', '(aspetta il sì)', 'Sono [nome], di DenkiCode. Le rubo trenta secondi, e le dico subito che al telefono non le vendo niente. Una domanda sola: i turni del personale, da voi chi li fa — lei o qualcun altro?'] },
    { t: 'note', text: '**"Al telefono non le vendo niente" è vero**, e toglie il motivo di riattaccare prima che venga in mente. La domanda è sul **loro** lavoro, non sul nostro prodotto: a "le interessa un software" non risponde nessuno, a "chi fa i turni" rispondono quasi tutti — e qualifica il decisore in quindici secondi.' },
    { t: 'p', text: 'Se **non è lui**:' },
    { t: 'say', lines: ['Mi può dire chi se ne occupa, e quando lo trovo? Richiamo io.'] },
    { t: 'note', text: 'Poi si segna **Non è il decisore** con nome e orario.' },

    { t: 'h', text: '2 · Fallo parlare', tag: 'tre domande, una alla volta. Dopo ognuna si sta zitti' },
    { t: 'say', lines: ['E quando salta qualcuno all’ultimo — uno che si dà malato — come fate a coprirlo? Li chiamate uno per uno?'] },
    { t: 'note', text: '**È la domanda più importante della telefonata**, e quasi tutti raccontano. Chi risponde *«eh, ci arrangiamo»* o *«scrivo sul gruppo WhatsApp»* si è appena qualificato da solo.' },
    { t: 'say', lines: ['E quando non trova nessuno, chi ci va? Le tocca coprire a lei?', '(ascolta)', 'Quante volte al mese le capita?'] },
    { t: 'note', text: '**Non commentare le risposte**: non serve dire "eh, immagino". Queste due domande mettono un prezzo sul problema — senza, il nostro sembra alto per confronto.' },
    { t: 'p', text: 'Poi una domanda di servizio, che serve a Patrick:' },
    { t: 'say', lines: ['E i turni li fate su carta, su Excel, o avete un gestionale?'] },

    { t: 'h', text: '3 · Di’ cosa facciamo' },
    { t: 'say', lines: ['Ecco, allora le dico in due parole perché la chiamo. Siamo una software house qui in Brianza e abbiamo fatto una cosa che serve esattamente a quello: lei costruisce la settimana una volta sola, ognuno si vede la sua sul telefono, e quando salta qualcuno il programma le dice subito chi è libero e chi ha già fatto troppe ore. Ferie e malattie entrano lì dentro senza rifare i conti a mano.'] },
    { t: 'note', text: 'Non si dice "gestionale innovativo", non si dice "soluzione". Si dice **cosa fa**.' },

    { t: 'h', text: '4 · Chiedi, una volta sola' },
    { t: 'say', lines: ['Glielo faccio vedere? Sono dieci minuti e glielo mostra il mio collega Patrick. Le va meglio in videochiamata, o passa lui da voi?', '(quando dice sì)', 'Perfetto. [Giorno] mattina o [giorno] pomeriggio?'] },

    { t: 'break' },
    { t: 'h', text: 'SE TI DICE… TU DICI' },
    { t: 'obj', q: 'Non mi interessa',
      lines: ['Ha ragione, e me lo dicono tutti — anche perché non le ho ancora detto niente. Una domanda sola e poi la lascio: quanto tempo le porta via fare i turni ogni settimana?', '(ascolta)', 'Ecco, è quello che togliamo. Dieci minuti per capire se le serve, e se non le serve non mi sente più.'] },
    { t: 'obj', q: 'Non ho tempo',
      lines: ['La capisco, per questo non le chiedo di decidere adesso. Sono dieci minuti e li sceglie lei: le va meglio [giorno] mattina presto, o a fine giornata?'],
      note: 'Si riduce **la richiesta**, mai il valore.' },
    { t: 'obj', q: 'Quanto costa?',
      lines: ['Su dieci dipendenti sono duecentoquaranta euro l’anno, una volta sola, una ricevuta sola. Glielo dico subito perché non mi piace girarci intorno — ma se non le risolve un problema il prezzo non conta niente. Per quello le chiedo dieci minuti.'],
      note: '**Il prezzo si dice come totale dell’anno, mai "2 € al mese a persona".** Un importo al mese per persona suona come una cosa che cresce e scappa di mano; 240 € una volta l’anno è una decisione che si prende subito. Il conto è lo stesso.' },
    { t: 'obj', q: 'Usiamo già Excel / abbiamo un gestionale',
      lines: ['Benissimo, allora sa già di cosa parlo: è la risposta migliore che potevo avere. Le faccio la domanda che conta: quando le salta una persona, Excel le dice chi è libero e chi è già a monte ore?', '(no)', 'Ecco, è l’unica differenza. Dieci minuti e vede se vale la pena.'],
      note: 'Chi ha già Excel **è un cliente migliore, non peggiore**: ha già capito da solo che il problema esiste.' },
    { t: 'obj', q: 'Siamo pochi',
      lines: ['Quante persone siete, se posso?', '(sotto le 8 si chiude bene e si va avanti)', 'Allora glielo dico sinceramente: per come siete messi voi non vale la pena. Se crescete si ricordi di noi, buona giornata.'],
      note: 'Chiudere una chiamata inutile in venti secondi è **produttività**, non una sconfitta. Si segna **Troppo piccoli**.' },
    { t: 'obj', q: 'Mi mandi una mail',
      lines: ['Volentieri, gliela mando subito. Però le dico come va a finire, con onestà: la mail resta lì e non la apre nessuno. Dieci minuti con Patrick e ha finito prima — [giorno] o [giorno]?'] },
    { t: 'obj', q: 'Chi siete? Non vi conosco',
      lines: ['Giusto. DenkiCode, siamo a Seveso, facciamo software su misura per le aziende qui in zona. Le lascio il sito così ci guarda con calma: denkicode.com.'] },
    { t: 'obj', q: 'Quando me lo attivate?',
      lines: ['Questo glielo faccio dire direttamente a Patrick: la data la dà lui quando ha visto come siete organizzati.'],
      note: '**Non si promette mai una data.** Il programma si mostra e si prova; la data la dà Patrick.' },

    { t: 'break' },
    { t: 'h', text: 'DOPO LA CHIAMATA', tag: 'nel foglio, prima una di queste sei parole' },
    { t: 'p', text: '**Non risponde · Richiamare · Non è il decisore · No · Troppo piccoli · Fissato incontro**' },
    { t: 'p', text: 'Poi quattro cose, o Patrick arriva alla demo cieco:' },
    { t: 'list', ordered: true, items: [
      '**quante persone** sono in squadra',
      '**chi fa i turni** oggi, e con cosa — carta, Excel, gestionale',
      '**dove perdono tempo**: sostituzioni? ferie? conteggio ore?',
      '**giorno e ora** dell’appuntamento, e se in call o dal vivo',
    ] },
    { t: 'h', text: 'Il messaggio, entro cinque minuti' },
    { t: 'say', lines: ['Buongiorno [Nome], sono [nome] di DenkiCode — ci siamo sentiti ora al telefono. Confermo [giorno] alle [ora]: il mio collega Patrick le fa vedere in dieci minuti come gestiamo i turni del personale. A presto!'] },
    { t: 'p', text: 'Se non ha fissato ma ha chiesto materiale:' },
    { t: 'say', lines: ['Buongiorno [Nome], sono [nome] di DenkiCode. Come promesso le lascio due righe: il nostro programma costruisce i turni della settimana, li manda sul telefono di ogni dipendente e quando salta qualcuno le dice subito chi è libero. Su dieci dipendenti sono 240 € l’anno. Qui trova chi siamo: denkicode.com — se vuole vederlo dal vivo sono dieci minuti, mi dica lei quando.'] },

    { t: 'h', text: 'I QUATTRO DIVIETI' },
    { t: 'list', ordered: true, items: [
      '**Nessuna data di attivazione.** Mai "partite lunedì", mai "in una settimana siete operativi". La demo si può fare oggi, la data la dà Patrick — chi promette una data la fa promettere a lui',
      '**Si dà del Lei**, sempre, anche con chi ha vent’anni',
      '**Il prezzo non si aggiusta**, e si dice **solo** come totale annuo',
      'Mai "abbonamento", "contratto", "fattura": si dice **ricevuta** e **quota annuale**',
    ] },
  ],
};
