module.exports = {
  file: 'script-indagine.docx',
  title: 'Indagine di mercato',
  product: 'Lo usiamo tutti e tre — Giulia, Gabriele, Edoardo. Dove c’è [nome] ci va il tuo.',
  objective: '**Obiettivo: il modulo compilato. Basta quello.**\n\n**Qui non si vende niente, e non è un modo di dire**: zero prodotti, zero prezzi, zero software nominati. Se nomini un programma, la ricerca diventa una scusa per vendere e la telefonata muore lì. È anche la posizione più forte della settimana: qui **non chiedi, dai**.',
  blocks: [
    { t: 'h', text: 'LA CHIAMATA' },

    { t: 'h', text: '1 · Apri' },
    { t: 'say', lines: ['Buongiorno, parlo con [nome dell’azienda]?', '(aspetta il sì)', 'Sono [nome], di DenkiCode. Le dico subito perché chiamo, così non le faccio perdere tempo: non le devo vendere niente. Stiamo facendo una ricerca sulle aziende di [settore] qui in zona — come gestite ordini, magazzino e rapportini. Sono tre domande.'] },
    { t: 'note', text: '**"Non le devo vendere niente" è letteralmente vero**, ed è il motivo per cui questa lista converte in modo diverso dalle altre. Chi lo dice e poi vende brucia la frase per tutte le liste future, di tutti e tre.' },

    { t: 'h', text: '2 · Le tre domande', tag: 'una alla volta, aspettando la risposta. Non è un questionario' },
    { t: 'say', lines: ['1. Oggi ordini e magazzino li tenete su un gestionale, su Excel, o su carta?'] },
    { t: 'say', lines: ['2. E c’è qualcosa che vi tocca ancora rifare a mano due volte — tipo riscrivere in ufficio quello che è già stato scritto in officina?'] },
    { t: 'say', lines: ['3. Se potesse cancellare un lavoro ripetitivo dalla settimana, quale toglierebbe per primo?'] },
    { t: 'note', text: '**La terza è quella che vale la telefonata. Poi silenzio.** Quella risposta è il capitolato di quello che Nicola costruirà: si scrive **con le sue parole**, non riassunta.' },

    { t: 'h', text: '3 · Una domanda in più' },
    { t: 'say', lines: ['E quante ore alla settimana se ne vanno lì, secondo lei?'] },
    { t: 'note', text: 'Non serve un numero preciso: serve che se lo chieda ad alta voce. Chi risponde *«troppe»* ha appena detto che il problema esiste.' },

    { t: 'h', text: '4 · Chiedi' },
    { t: 'p', text: '**Prima strada, e la migliore: lo compili tu mentre siete al telefono.**' },
    { t: 'say', lines: ['Guardi, faccio così: queste risposte le metto io nel modulo della ricerca, le rubo altri due minuti e non deve fare niente. Le va?'] },
    { t: 'p', text: '**Seconda strada, se ha fretta:**' },
    { t: 'say', lines: ['Le mando il link su WhatsApp: sono otto domande, tre minuti, e lo fa quando ha un attimo. Su questo numero?'] },
    { t: 'p', text: '**E si dà sempre qualcosa in cambio** — è una ricerca, non un favore:' },
    { t: 'say', lines: ['Quando abbiamo finito di girare le aziende della zona le mando il riepilogo di cosa è venuto fuori: chi usa cosa, e dove perdono più tempo tutti. Almeno sa come sono messi gli altri.'] },

    { t: 'break' },
    { t: 'h', text: 'SE TI DICE… TU DICI' },
    { t: 'obj', q: 'Non ho tempo',
      lines: ['La capisco, chiamo in orario di lavoro. Sono tre domande e le faccio io, non deve compilare niente. Le va se gliele faccio adesso in due minuti, o la richiamo dopo le [ora]?'] },
    { t: 'obj', q: 'A cosa vi serve? Cosa ci guadagnate?',
      lines: ['Domanda giusta. Siamo una software house di Seveso: prima di costruire qualcosa vogliamo capire come lavorano davvero le aziende qui, invece di immaginarcelo dalla scrivania. Se poi da quello che ci dice esce un’idea utile gliela portiamo, e decide lei se le serve. Intanto le faccio le tre domande?'],
      note: '**Onestà completa**: non si finge una ricerca universitaria e non si dice "studio di settore indipendente". Siamo una software house che studia il mercato, e detto così regge.' },
    { t: 'obj', q: 'Siamo a posto, abbiamo già un gestionale',
      lines: ['Buon per voi, è la risposta che sento meno spesso — e proprio per questo mi interessa: quale usate, e cosa vi tocca fare lo stesso a mano nonostante ce l’abbiate?'],
      note: 'Chi ha già un gestionale **è il contatto più prezioso della lista**: sa esattamente dove quel gestionale non arriva, e quel buco è il prodotto.' },
    { t: 'obj', q: 'Non compilo moduli online',
      lines: ['Ci mancherebbe, glielo compilo io: le faccio le domande, metto giù le risposte e lei non tocca niente. Partiamo dalla prima?'] },
    { t: 'obj', q: 'Mi mandi una mail',
      lines: ['Volentieri, le mando il link. Le dico com’è però: i moduli via mail non li apre nessuno, e sarebbe un peccato perché la vostra è esattamente l’azienda che ci serve. Facciamo che gliele faccio adesso, sono due minuti?'] },
    { t: 'obj', q: 'Non do informazioni sull’azienda',
      lines: ['Fa benissimo, e non le chiedo numeri: né fatturato né clienti. Le chiedo solo che programmi usate e cosa vi fa perdere tempo. Su questo posso?'] },
    { t: 'obj', q: 'Chi siete?',
      lines: ['DenkiCode, siamo di Seveso, facciamo software su misura per le aziende qui in zona. Le lascio l’indirizzo: denkicode.com.'] },

    { t: 'break' },
    { t: 'h', text: 'DOPO LA CHIAMATA', tag: 'anche senza modulo, queste quattro cose valgono la telefonata' },
    { t: 'p', text: 'Nel foglio, dopo la parola d’esito:' },
    { t: 'list', ordered: true, items: [
      '**cosa usano oggi** — gestionale (quale), Excel, carta',
      'il **doppio lavoro** che hanno ammesso: cosa si riscrive due volte',
      'il **lavoro ripetitivo** che toglierebbero per primo, **con le sue parole**',
      '**quante persone** ci lavorano dentro, e chi decide sui programmi',
    ] },
    { t: 'h', text: 'I messaggi' },
    { t: 'p', text: 'Se hai compilato tu, al telefono:' },
    { t: 'say', lines: ['Buongiorno [Nome], sono [nome] di DenkiCode. Grazie per i due minuti: ho messo le sue risposte nella ricerca. Le mando il riepilogo appena abbiamo finito il giro delle aziende della zona.'] },
    { t: 'p', text: 'Se ha chiesto il link:' },
    { t: 'say', lines: ['Buongiorno [Nome], sono [nome] di DenkiCode, ci siamo sentiti ora. Le lascio il modulo della ricerca, sono otto domande e tre minuti: [link] — quando abbiamo finito le mando cosa è venuto fuori dalle aziende della zona.'] },
    { t: 'p', text: 'Se dopo sette giorni il link non è stato compilato, due righe:' },
    { t: 'say', lines: ['Buongiorno [Nome], [nome] di DenkiCode. Ha lasciato perdere la ricerca?'] },

    { t: 'h', text: 'I QUATTRO DIVIETI' },
    { t: 'list', ordered: true, items: [
      '**Non si nomina nessun prodotto, nessun prezzo, nessuna demo**: è il divieto che tiene in piedi tutta la lista',
      'Non si dice "gestionale su misura" né "sviluppiamo per voi": quello è il lavoro di Patrick, dopo il prototipo',
      'Non si dice "ricerca indipendente" né "studio di settore": siamo una software house e lo si dice',
      '**Il riepilogo promesso va mandato davvero**, o la promessa costa più di quello che ha reso',
    ] },
  ],
};
