module.exports = {
  file: 'script-giulia-denkishift.docx',
  title: 'DenkiShift · turni',
  product: 'Prodotto C · RSA, cooperative, imprese di pulizie, locali con personale a turni',
  objective: '**Obiettivo della chiamata: fissare la demo con Patrick. Nient’altro.** Non chiudi, non mandi preventivi, non prometti date di attivazione.',
  blocks: [
    { t: 'h', text: 'Le regole, prima di comporre il numero' },
    { t: 'table', widths: [3100, 6640], head: ['Regola', 'In pratica'],
      rows: [
        ['Sempre del **"Lei"**', 'Anche se dall’altra parte ti danno del tu'],
        ['**Non chiudi tu**', 'Il traguardo è la demo di dieci minuti con Patrick'],
        ['**Nessuna data di attivazione**', 'Il software si può **mostrare**, non ancora installare. Mai "partite lunedì"'],
        ['Parole vietate', '**Mai** "abbonamento", "contratto", "fattura". Si dice **due euro al mese a persona**'],
        ['Sotto le 8 persone', 'Non è un cliente. Si chiude bene in venti secondi e si va avanti'],
      ] },

    { t: 'h', text: '1. Apertura — i primi otto secondi', tag: 'Voss — questa settimana se ne provano due, vedi sotto' },
    { t: 'say', lines: ['Buongiorno, parlo con [nome dell’attività]?', '(aspetta il sì)', 'Perfetto. Guardi, le rubo trenta secondi e le dico subito che al telefono non le vendo niente. Una domanda sola: chi si occupa dei turni del personale da voi — lei o qualcun altro?'] },
    { t: 'note', text: '**«Non le vendo niente» è letteralmente vero** — tu non chiudi mai — e disinnesca il riflesso di riattaccare prima che parta. La domanda che segue è sul **loro** lavoro: nessuno risponde a "le interessa un software", quasi tutti rispondono a "chi fa i turni". Va detta piano: se corri, "trenta secondi" suona come ogni call center.' },
    { t: 'p', text: 'Se non è la persona giusta:' },
    { t: 'say', lines: ['Mi può dire chi se ne occupa, e quando lo trovo? Richiamo io.'] },
    { t: 'note', text: 'Si segna **Non è il decisore**, con nome e orario.' },

    { t: 'h', text: '2. La domanda che apre il dolore', tag: 'SPIN — Problema' },
    { t: 'say', lines: ['E quando salta qualcuno all’ultimo — una malattia, un imprevisto — come fate a coprirlo? Chiamate uno per uno?'] },
    { t: 'note', text: '**Poi si sta zitti.** È la domanda più importante della chiamata e quasi tutti raccontano. Chi risponde *«eh, ci arrangiamo»* o *«scrivo sul gruppo WhatsApp»* si è appena qualificato da solo.' },
    { t: 'say', lines: ['E i turni li fate su carta, su Excel, o avete un gestionale?'] },
    { t: 'note', text: 'Due informazioni che servono a Patrick, prese senza sembrare un questionario.' },

    { t: 'h', text: '3. Il costo del buco', tag: 'SPIN — Implicazione. È la parte aggiunta il 28/08' },
    { t: 'say', lines: ['E quando non trova nessuno, chi ci va? Le tocca coprire a lei?', '(ascolta)', 'Quante volte al mese le succede?'] },
    { t: 'note', text: 'Senza questa domanda resta un problema ammesso **ma senza prezzo**, e allora qualunque cifra sembra alta. Con questa, il responsabile ha appena detto ad alta voce quante sere si è rovinato quest’anno. Non si commenta la risposta: si va avanti.' },

    { t: 'h', text: '4. Il valore, in quattro righe' },
    { t: 'say', lines: ['Ecco, allora le dico in due parole perché la chiamo. Siamo una software house qui in Brianza e abbiamo fatto una cosa che serve esattamente a quello: il responsabile costruisce la settimana una volta sola, ognuno vede la sua sul telefono, e quando salta qualcuno il sistema le dice subito chi è libero e chi è già sopra le sue ore. Ferie e malattie entrano lì dentro senza rifare i conti a mano.'] },
    { t: 'note', text: 'Non si dice "gestionale innovativo", non si dice "soluzione". Si dice **cosa fa**.' },

    { t: 'h', text: '5. La domanda, una sola' },
    { t: 'say', lines: ['Glielo faccio vedere? Sono dieci minuti, glielo mostra il mio collega Patrick. Le va meglio in videochiamata, o passiamo noi in negozio?'] },
    { t: 'note', text: 'Doppia scelta, **entrambe un sì**. Mai *«le interesserebbe vederlo?»*. Quando dice sì: *«Perfetto. [Giorno] mattina o [giorno] pomeriggio?»*' },

    { t: 'break' },
    { t: 'h', text: 'Le due aperture in prova questa settimana', tag: 'si segna la sigla nella colonna Note: PI-1 oppure PI-3' },
    { t: 'p', text: '**PI-1 — il disarmo** (è quella qui sopra, al punto 1): toglie il motivo di riattaccare prima che venga in mente.' },
    { t: 'p', text: '**PI-3 — il no anticipato**: dice di no al posto suo e lo lascia contraddire.' },
    { t: 'say', lines: ['Buongiorno. Guardi, probabilmente non fa per voi, e glielo dico prima io. Però se i turni del personale li fate ancora a mano — su carta o su un foglio Excel — allora forse vale trenta secondi. Come li fate?'] },
    { t: 'note', text: '**La domanda finale va fatta sempre, subito dopo la virgola**: se la lasci cadere, lui raccoglie il "non fa per voi" e chiude. Metà chiamate con PI-1, metà con PI-3, e la sigla nella colonna Note: a fine settimana si contano gli appuntamenti per sigla.' },

    { t: 'h', text: 'Le obiezioni', tag: 'valida, riporta al valore, richiedi. "Ha ragione" è quasi sempre la prima parola' },
    { t: 'obj', q: 'Non mi interessa',
      lines: ['Ha ragione, e me lo dicono tutti — anche perché non le ho ancora detto niente. Una domanda sola e poi la lascio: quanto tempo le porta via fare i turni ogni settimana?', '(ascolta)', 'Ecco, è quello che togliamo. Dieci minuti per capire se le serve. Se non le serve, non ci sente più.'] },
    { t: 'obj', q: 'Non ho tempo',
      lines: ['La capisco, per questo non le chiedo di decidere adesso. Sono dieci minuti e li sceglie lei: le va meglio [giorno] mattina presto o a fine giornata?'],
      note: 'Non si riduce il valore, si riduce la richiesta.' },
    { t: 'obj', q: 'Quanto costa?',
      lines: ['Due euro al mese a persona, e li paga l’azienda. Su dieci dipendenti sono venti euro al mese. Glielo dico subito perché non mi piace girarci intorno — ma se non le risolve un problema, il prezzo non conta niente. Per quello le chiedo dieci minuti.'],
      note: 'Si dice **«due euro al mese a persona»**. Mai "abbonamento", mai "contratto". Un prezzo diverso non si improvvisa: lo aggiusta Patrick.' },
    { t: 'obj', q: 'Usiamo già Excel / abbiamo già un gestionale',
      lines: ['Benissimo, allora sa già di cosa parlo — è la risposta migliore che potevo avere. Le faccio la domanda che conta: quando le salta una persona, Excel le dice chi è libero e chi è già a monte ore?', '(no)', 'Ecco, è l’unica differenza. Dieci minuti e vede se vale la pena.'],
      note: 'Chi ha già Excel **è un cliente migliore**, non peggiore: ha già capito che il problema esiste.' },
    { t: 'obj', q: 'Mi mandi una mail / del materiale',
      lines: ['Volentieri, gliela mando subito. Però le dico come va a finire, con onestà: la mail resta lì e non la apre nessuno. Dieci minuti con Patrick e ha finito prima — [giorno] o [giorno]?'],
      note: 'Se insiste: si manda davvero il messaggio e si segna **Richiamare** con la data.' },
    { t: 'obj', q: 'Siamo pochi',
      lines: ['Quante persone siete, se posso?', '(sotto le 8 non è un cliente)', 'Allora guardi, glielo dico sinceramente: per come siete messi voi non vale la pena. Se crescete si ricordi di noi. Buona giornata.'],
      note: 'Chiudere una chiamata inutile in venti secondi è **produttività**, non una sconfitta. Si segna **Troppo piccoli**.' },
    { t: 'obj', q: 'Chi siete? Non vi conosco',
      lines: ['Giusto. DenkiCode, siamo a Seveso, facciamo software su misura per aziende qui in zona. Le lascio il sito, così ci guarda con calma: denkicode.com.'] },

    { t: 'h', text: 'Cosa passo a Patrick', tag: 'senza queste quattro cose arriva alla demo cieco' },
    { t: 'list', ordered: true, items: [
      '**Quante persone** in squadra',
      '**Chi fa i turni** oggi, e con cosa: carta, Excel, gestionale',
      '**Dove perdono tempo**: sostituzioni? ferie? conteggio ore?',
      '**Giorno e ora** dell’appuntamento, e se in call o dal vivo',
    ] },

    { t: 'h', text: 'I messaggi dopo la chiamata' },
    { t: 'p', text: '**Appuntamento fissato** — entro cinque minuti:' },
    { t: 'say', lines: ['Buongiorno [Nome], sono Giulia di DenkiCode — ci siamo sentiti ora al telefono. Confermo [giorno] alle [ora]: il mio collega Patrick le fa vedere in dieci minuti come gestiamo i turni del personale. A presto!'] },
    { t: 'p', text: '**Niente appuntamento, ma ha chiesto materiale:**' },
    { t: 'say', lines: ['Buongiorno [Nome], sono Giulia di DenkiCode. Come promesso le lascio due righe: il nostro software costruisce i turni della settimana, li manda sul telefono di ogni dipendente e quando salta qualcuno le dice subito chi è libero. Due euro al mese a persona. Qui trova chi siamo: denkicode.com — se vuole vederlo dal vivo sono dieci minuti, mi dica lei quando.'] },

    { t: 'h', text: 'Quello che non si dice mai' },
    { t: 'table', widths: [4200, 5540], head: ['Mai', 'Perché'],
      rows: [
        ['**Una data di attivazione** — "partite lunedì", "in una settimana siete operativi"', 'Il software non è ancora installabile in produzione. La demo si può fare, l’attivazione no'],
        ['"abbonamento", "contratto", "fattura"', 'Si dice **due euro al mese a persona**'],
        ['"gestionale innovativo", "soluzione all’avanguardia"', 'Si dice cosa fa la cosa'],
        ['Un prezzo diverso da 2 € a persona al mese', 'Il prezzo lo aggiusta Patrick, non si improvvisa al telefono'],
      ] },
  ],
};
